apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  secretObjects:
    - secretName: my-secret
      type: Opaque
      data:
        - objectName: mySecret
  parameters:
    usePodIdentity: "true"
    keyvaultName: "myKeyVault"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: mySecret
          objectType: secret
          objectVersion: ""
    tenantId: "<TenantID>"
